# Generated by Django 2.2.7 on 2019-11-27 21:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Event_id', models.CharField(default='', max_length=30)),
                ('Event_name', models.CharField(default='', max_length=30)),
                ('Event_description', models.TextField(blank=True)),
                ('Event_category', models.CharField(choices=[('Conference', 'Conference'), ('Seminar', 'Seminar'), ('Presentation', 'Presentation')], default='Conference', max_length=30)),
                ('Event_start_date', models.DateField()),
                ('Event_end_date', models.DateField()),
                ('Event_start_time', models.TimeField()),
                ('Event_end_time', models.TimeField()),
                ('Event_location', models.CharField(default='', max_length=30)),
                ('Allow_registration', models.BooleanField(default=True)),
                ('Event_image', models.ImageField(blank=True, upload_to='products/%Y/%m/%d')),
                ('Adult_ticket_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Child_ticket_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('published_date', models.DateTimeField(blank=True, null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
