# Generated by Django 2.2.7 on 2019-11-28 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Event', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='Event_end_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='event',
            name='Event_start_date',
            field=models.DateTimeField(),
        ),
    ]
