# Generated by Django 2.2.7 on 2019-11-29 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Event', '0002_auto_20191128_2005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='Event_end_date',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='event',
            name='Event_end_time',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='event',
            name='Event_start_date',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='event',
            name='Event_start_time',
            field=models.DateField(),
        ),
    ]
