# Generated by Django 2.2.7 on 2019-11-29 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Event', '0003_auto_20191129_1518'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='Event_end_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='event',
            name='Event_end_time',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='event',
            name='Event_start_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='event',
            name='Event_start_time',
            field=models.TimeField(),
        ),
    ]
