# Generated by Django 2.2.7 on 2019-12-03 18:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Event', '0005_auto_20191202_1558'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='Total_adult_qty',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AlterField(
            model_name='registration',
            name='Total_child_qty',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
