# Generated by Django 2.2.7 on 2019-12-22 03:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Event', '0007_auto_20191219_2038'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registration',
            name='author',
        ),
    ]
