# Generated by Django 2.2.7 on 2019-12-22 03:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Event', '0008_remove_registration_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='Total_adult_qty',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(50)]),
        ),
        migrations.AlterField(
            model_name='registration',
            name='Total_child_qty',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(50)]),
        ),
    ]
