# Generated by Django 2.2.7 on 2019-12-23 04:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Event', '0009_auto_20191222_0338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='Total_adult_qty',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='registration',
            name='Total_child_qty',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
