# Generated by Django 2.2.7 on 2019-12-23 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Event', '0011_remove_event_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='Adult_ticket_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='event',
            name='Child_ticket_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='event',
            name='Event_end_date',
            field=models.DateField(default='2019-12-12'),
        ),
        migrations.AlterField(
            model_name='event',
            name='Event_end_time',
            field=models.TimeField(default='08:00:00'),
        ),
        migrations.AlterField(
            model_name='event',
            name='Event_start_date',
            field=models.DateField(default='2019-12-12'),
        ),
        migrations.AlterField(
            model_name='event',
            name='Event_start_time',
            field=models.TimeField(default='06:00:00'),
        ),
    ]
