# Generated by Django 2.2.7 on 2019-12-23 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Event', '0013_auto_20191223_2024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='Event_image',
            field=models.ImageField(blank=True, default='', upload_to='event/%Y/%m/%d'),
        ),
    ]
