# Generated by Django 2.2.7 on 2019-12-23 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Event', '0015_auto_20191223_2026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='Event_image',
            field=models.FileField(blank=True, upload_to='event/%Y/%m/%d'),
        ),
    ]
