# Generated by Django 2.2.7 on 2019-12-23 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Event', '0016_auto_20191223_2057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='Event_image',
            field=models.ImageField(blank=True, upload_to='event/%Y/%m/%d'),
        ),
    ]
