# Generated by Django 2.2.7 on 2019-12-23 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Event', '0017_auto_20191223_2100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='Event_image',
            field=models.ImageField(blank=True, default='/media/event/2019/12/20/event4.jpg', upload_to='event/%Y/%m/%d'),
        ),
    ]
